# Generated by Django 5.2 on 2025-05-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
